name: Build hostsfile
on:
  push:
    paths:
      - 'data/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Execute building
        run: python createHosts.py

      - name: Publish new hosts files
        run: |
          git config --global user.name "user name"
          git config --global user.email "user email"

          git add -A
          git commit -m "programmatically updated hostfiles"
          git push